---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.autoscaler_name }}
  namespace: {{ .Values.eksNamespace }}
  labels:
    app: {{ .Values.autoscaler_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.autoscaler_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.autoscaler_name }}
        app.kubernetes.io/managed-by: Helm
        meta.helm.sh/release-name: autoscaler
        meta.helm.sh/release-namespace: deafult
      annotations:
        # prometheus.io/scrape: 'true'
        # prometheus.io/port: '8085'
    spec:
      priorityClassName: system-cluster-critical
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ .Values.autoscaler_name }}
      containers:
        - image: {{ .Values.image.name }}
          name: {{ .Values.autoscaler_name }}
          resources:
            limits:
              cpu: 100m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 600Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --skip-nodes-with-system-pods=false
            - --expander=least-waste
            - --aws-use-static-instance-list=true
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/cve-eks
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt # /etc/ssl/certs/ca-bundle.crt for Amazon Linux Worker Nodes
              readOnly: true
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-bundle.crt"